import { useEffect } from 'react'
import { useUiStrings } from '../i18n/UiStringsContext'
import { WAND_STATUS } from '../hooks/useMagicWand'
import { SUGGESTION_MODE, isParticipantMode } from '../services/Suggestions'

const ACCENT = '#c084fc'
const MODAL_WIDTH = 420

/** The same working spinner the chat uses, so "busy" looks the same everywhere. */
function SpinnerIcon({ size = 15 }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ animation: 'spin 1s linear infinite' }} aria-hidden="true" focusable="false">
      <path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83" />
    </svg>
  )
}

/**
 * Sparkles rather than a wand: at this size a wand reads as generic "magic",
 * while sparkles are the established mark for "generated by a model". Filled
 * shapes stay crisp at 15px, where thin strokes would turn to mush.
 */
function WandIcon({ size = 15 }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false">
      <path d="M9.5 4 Q10.5 10.9 17 12 Q10.5 13.1 9.5 20 Q8.5 13.1 2 12 Q8.5 10.9 9.5 4Z" />
      <path d="M19 2 Q19.4 4.6 22 5 Q19.4 5.4 19 8 Q18.6 5.4 16 5 Q18.6 4.6 19 2Z" />
      <path d="M19 15 Q19.4 17.1 21.5 17.5 Q19.4 17.9 19 20 Q18.6 17.9 16.5 17.5 Q18.6 17.1 19 15Z" />
    </svg>
  )
}

/**
 * Wand button plus the popover listing what the model came up with.
 * `mode` identifies which caller opened it, so two wands can share one hook
 * without showing each other's results.
 */
export default function MagicWand({ wand, mode, onPick, disabled = false, describeItem = null }) {
  const UI_STRINGS = useUiStrings()
  const ui = UI_STRINGS.app
  const isActive = wand.mode === mode
  const isOpen = isActive && wand.status !== WAND_STATUS.IDLE

  useEffect(() => {
    if (!isOpen) return
    const handler = event => {
      if (event.key === 'Escape') wand.close()
    }
    document.addEventListener('keydown', handler)
    return () => document.removeEventListener('keydown', handler)
  }, [isOpen, wand])

  const unavailable = disabled || !wand.available
  const title = wand.unavailableReason === 'offline' ? ui.wandOffline
    : wand.unavailableReason === 'noModel' ? ui.wandNoModel
    : ui.wandTitle

  return (
    <div style={{ position: 'relative', flexShrink: 0 }}>
      <button
        type="button"
        onClick={() => (isOpen ? wand.close() : wand.generate(mode))}
        disabled={unavailable || (wand.isLoading && isActive)}
        title={title}
        aria-label={title}
        style={{
          background: isActive && isOpen ? '#2a1f3a' : 'transparent',
          border: `1px solid ${isActive && isOpen ? ACCENT : '#2e2e2e'}`,
          borderRadius: 6,
          color: unavailable ? '#3a3a3a' : (isActive && isOpen ? ACCENT : '#777'),
          cursor: unavailable ? 'default' : 'pointer',
          padding: '4px 7px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          transition: 'all 0.15s',
        }}
      >
        <span style={{ display: 'flex' }}>
          {isActive && wand.isLoading ? <SpinnerIcon /> : <WandIcon />}
        </span>
      </button>

      {isOpen && (
        <div
          role="presentation"
          onMouseDown={event => { if (event.target === event.currentTarget) wand.close() }}
          style={{ position: 'fixed', inset: 0, zIndex: 1000, background: '#00000066', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 12, boxSizing: 'border-box' }}
        >
          <div
            role="dialog"
            aria-modal="true"
            aria-label={isParticipantMode(mode) ? ui.wandParticipantTitle : mode === SUGGESTION_MODE.CONCLUSION ? ui.wandConclusionTitle : ui.wandSteerTitle}
            onMouseDown={event => event.stopPropagation()}
            style={{ width: MODAL_WIDTH, maxWidth: 'calc(100vw - 24px)', maxHeight: 'calc(100vh - 24px)', background: '#1a1622', border: `1px solid ${ACCENT}55`, borderRadius: 10, boxShadow: '0 6px 24px #000a', overflow: 'hidden', display: 'flex', flexDirection: 'column' }}
          >
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, padding: '7px 10px', borderBottom: '1px solid #2e2438', flexShrink: 0 }}>
            <span style={{ fontSize: 10, color: ACCENT, letterSpacing: 0.6, textTransform: 'uppercase', fontWeight: 700 }}>
              {isParticipantMode(mode) ? ui.wandParticipantTitle
                : mode === SUGGESTION_MODE.CONCLUSION ? ui.wandConclusionTitle
                : ui.wandSteerTitle}
            </span>
            <span style={{ fontSize: 10, color: '#6b6b6b', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: 150 }} title={wand.model}>
              {wand.model}
            </span>
          </div>

          {wand.status === WAND_STATUS.LOADING && (
            <div style={{ padding: '12px 12px', fontSize: 12, color: '#8a8a8a' }}>
              {isParticipantMode(mode) ? ui.wandLoadingParticipant : ui.wandLoading}
            </div>
          )}

          {wand.status === WAND_STATUS.ERROR && (
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, padding: '10px 12px' }}>
              <span style={{ fontSize: 11, color: '#f87171' }}>{wand.error || ui.wandEmpty}</span>
              <button
                type="button"
                onClick={() => wand.generate(mode)}
                style={{ background: 'transparent', border: '1px solid #3a3a3a', color: '#999', borderRadius: 6, padding: '3px 10px', cursor: 'pointer', fontSize: 11, flexShrink: 0 }}
              >{ui.wandRetry}</button>
            </div>
          )}

          {wand.status === WAND_STATUS.READY && (
            <>
              <div style={{ maxHeight: 260, overflowY: 'auto' }}>
                {wand.suggestions.map((suggestion, index) => {
                // Steer/conclusion yield plain strings; participant mode yields
                // a persona draft that needs its own summary line.
                const isDraft = typeof suggestion === 'object' && suggestion !== null
                const key = isDraft ? `${index}-${suggestion.name}` : `${index}-${suggestion.slice(0, 24)}`
                return (
                  <button
                    key={key}
                    type="button"
                    onClick={() => { onPick(suggestion); wand.close() }}
                    style={{
                      display: 'block',
                      width: '100%',
                      textAlign: 'left',
                      background: 'transparent',
                      border: 'none',
                      borderBottom: index < wand.suggestions.length - 1 ? '1px solid #241d30' : 'none',
                      color: '#d6d0e0',
                      fontSize: 12,
                      lineHeight: 1.5,
                      padding: '9px 12px',
                      cursor: 'pointer',
                    }}
                    onMouseEnter={event => { event.currentTarget.style.background = '#241d30' }}
                    onMouseLeave={event => { event.currentTarget.style.background = 'transparent' }}
                  >
                    {isDraft ? (
                      <>
                        <span style={{ display: 'block', color: '#e8e2f2', fontWeight: 700 }}>{suggestion.name}</span>
                        {describeItem?.(suggestion) && (
                          <span style={{ display: 'block', color: ACCENT, fontSize: 10, marginTop: 1 }}>{describeItem(suggestion)}</span>
                        )}
                        {suggestion.traits?.length > 0 && (
                          <span style={{ display: 'block', color: '#9c94ab', fontSize: 11, marginTop: 3 }}>
                            {suggestion.traits.join(' ')}
                          </span>
                        )}
                      </>
                    ) : suggestion}
                  </button>
                )
                })}
              </div>
              <div style={{ padding: '7px 10px', borderTop: '1px solid #2e2438' }}>
                <button
                  type="button"
                  onClick={() => wand.generate(mode)}
                  disabled={wand.isLoading}
                  style={{ width: '100%', background: '#241d30', border: '1px solid #4a3a5c', color: ACCENT, borderRadius: 6, padding: '5px 8px', cursor: wand.isLoading ? 'default' : 'pointer', fontSize: 11 }}
                >{ui.wandRegenerate}</button>
              </div>
            </>
          )}
          </div>
        </div>
      )}
    </div>
  )
}
